version: '3'

services:
  frontbuilder:
    build:
      context: ./
      dockerfile: docker/front.docker
    volumes:
      - ./front/src:/app/src
      - ./shared:/app/dist
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080
