version: '3'

services:

  metta-front:
    build:
      context: .
      dockerfile: ./docker/front.docker
    volumes:
      - ./front/src:/app/src
      - ./files/shared:/app/shared
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080

  metta-back:
    build:
      context: .
      dockerfile: ./docker/back.docker
    tty: true
    stdin_open: true
    volumes:
      - ./back:/app/src
      - ./files/shared:/app/shared
      - ./files/session:/app/session
    environment:
      - DEBUG=False
    env_file: .env
    command: >
      sh -c "
        pipenv run python /app/src/main.py
      "

  metta-proxy:
    build:
      context: ./docker/nginx
    ports:
      - 8888:8888

volumes:
  db_volume: {}
