version: '3'

services:

  metta-front:
    build:
      context: .
      dockerfile: ./front.docker
    volumes:
      - ./front/src:/app/src
      - ./shared:/app/dist
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080
    networks:
      - metta_network

  metta-back:
    build:
      context: .
      dockerfile: ./back.docker
    restart: unless-stopped
    env_file: '.env'
    stdin_open: true
    tty: true
    environment:
      - DOCKER=True
      - DEBUG=True
      - PIPENV_PIPFILE=/.metta/Pipfile
      - SESSION_FILE=/app/session/.session
      - SHARED=/app/shared
    env_file: .env
    volumes:
      - ./back:/app
      - ./shared:/app/shared
      - ./files/session:/app/session
    command: >
      sh -c "cd /.metta/ && pipenv run python /app/main.py"
    ports:
      - 5000:5000
    networks:
      - metta_network


networks:
  metta_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
