version: '3'

services:

  metta-front:
    build:
      context: .
      dockerfile: ./front.docker
    volumes:
      - ./front/src:/app/src
      - ./shared:/app/dist
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080

  metta-proxy:
    build:
      context: ./nginx
    ports:
      - 80:80

  metta-back:
    build:
      context: .
      dockerfile: ./back.docker
    restart: unless-stopped
    env_file: '.env'
    stdin_open: true
    tty: true
    volumes:
      - ./back:/app/src
      - ./files/shared:/app/shared
      - ./files/session:/app/session
    environment:
      - DOCKER=True
      - DEBUG=False
      - SESSION=/app/session
      - SHARED=/app/shared
      - PIPENV_PIPFILE=/.metta/Pipfile
    env_file: .env
    command: >
      sh -c "cd /.metta/ && pipenv run python /app/src/main.py"