version: '3'

services:

  metta-front:
    build:
      context: .
      dockerfile: ./front.docker
    volumes:
      - ./front/src:/app/src
      - ./files/shared:/app/shared
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080

  metta-back:
    build:
      context: .
      dockerfile: ./back.docker
    tty: true
    stdin_open: true
    volumes:
      - ./back:/app/src
      - ./files/shared:/app/shared
      - ./files/session:/app/session
    environment:
      - DEBUG=False
    env_file: .env
    command: >
      sh -c "cd /.metta/ && pipenv run python /app/src/main.py"

  metta-proxy:
    build:
      context: ./nginx
    ports:
      - 80:80

  metta-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file: .env

volumes:
  db_volume: {}