version: '3'

services:

  metta-front:
    build:
      context: .
      dockerfile: ./docker/front.docker
    volumes:
      - ./front/src:/app/src
      - ./files/shared:/app/shared
    command: >
      sh -c "npm run dev"
    ports:
      - 8080:8080

  metta-back:
    build:
      context: .
      dockerfile: ./docker/back.docker
    tty: true
    stdin_open: true
    volumes:
      - ./back:/app/src
      - ./files/shared:/app/shared
      - ./files/session:/app/session
    environment:
      - DEBUG=False
    env_file: .env
    command: >
      sh -c "
        ./wait-for-it.sh metta-db:5432 &&
        pipenv run python /app/src/main.py
      "

  metta-proxy:
    build:
      context: ./docker/nginx
    ports:
      - 8090:80

  metta-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_NAME=$DB_NAME

volumes:
  db_volume: {}